#!/bin/bash

# javac Crawler.java
echo "Compiling..."
javac -cp \
  '.:./commons-cli.jar:./mysql-connector-java-3.1.15-bin.jar:./mariadb-java-client-1.1.8.jar:' \
  Crawler.java

echo "Running..."
java -cp \
  '.:./commons-cli.jar:./mysql-connector-java-3.1.15-bin.jar:./mariadb-java-client-1.1.8.jar:' \
  Crawler "$@"
